#!/usr/bin/env python3
"""Generate the split sem-localize files from translations.json (#738).

The single-file sem-localize.js had grown to 1.2 MB — 16 languages parsed
by every browser to use exactly one. The split:

- ``sem-localize.js`` — the LOADER. Ships the full **English** table
  inline (fallback floor: worst case is English text, never raw keys),
  resolves the user's language (localStorage ``selectedLanguage`` →
  ``navigator.language`` → en), and lazily injects exactly one sibling
  ``sem-localize.<lang>.js``. Dispatches ``sem-localize-ready`` once at
  parse end (English usable immediately) and the sibling dispatches it
  again on arrival — cards already re-render on that event (#453), so
  the late language upgrade is free.
- ``sem-localize.<lang>.js`` ×15 — one table each, registered onto
  ``window.__semLocalizeTables``.

Contract kept bit-for-bit (#240 class): IIFE, ``window.semLocalize``,
``sem-localize-ready`` on document. Regenerate with:

    python3 dashboard/card/build_localize.py
"""
from __future__ import annotations

import json
import os
from datetime import datetime, timezone

HERE = os.path.dirname(os.path.abspath(__file__))
TRANSLATIONS = os.path.join(HERE, "..", "translations.json")

LOADER_TEMPLATE = """// Auto-generated by build_localize.py from translations.json — do not edit manually
// Generated: {stamp}
// (#738) Split loader: English inline as the fallback floor; the user's
// language is lazily injected as a sibling sem-localize.<lang>.js which
// re-dispatches ``sem-localize-ready`` (cards re-render on it, #453).
(function() {{
  if (typeof window === 'undefined') return;
  var tables = window.__semLocalizeTables = window.__semLocalizeTables || {{}};
  tables.en = {en_table};
  var requested = {{ en: true }};

  // The loader's own URL carries the cache-bust token (?v=... hashed from
  // translations.json at registration) — siblings must carry the SAME
  // token or a language change would serve a stale sibling forever.
  //
  // Discovery must survive ALL load channels: as a Lovelace *module*
  // resource HA fetches this file via dynamic import(), so there is NO
  // script tag and document.currentScript is null — the performance
  // resource entries are the one place the fetched URL always appears.
  function ownUrl() {{
    if (document.currentScript && document.currentScript.src)
      return document.currentScript.src;
    var tag = document.querySelector('script[src*="sem-localize.js"]');
    if (tag && tag.src) return tag.src;
    try {{
      var entries = performance.getEntriesByType('resource');
      for (var i = entries.length - 1; i >= 0; i--) {{
        if (entries[i].name.indexOf('sem-localize.js') !== -1)
          return entries[i].name;
      }}
    }} catch (e) {{ /* no performance API — resolved below as '' */ }}
    return '';
  }}
  var src = ownUrl();
  var base = src.split('?')[0].replace(/sem-localize\\.js$/, '');
  var query = src.indexOf('?') >= 0 ? src.slice(src.indexOf('?')) : '';

  function baseLang(lang) {{
    return String(lang || 'en').toLowerCase().split('-')[0];
  }}

  function ensure(lang) {{
    var b = baseLang(lang);
    if (!b || b === 'en' || requested[b] || !base) return;
    requested[b] = true;
    var s = document.createElement('script');
    s.src = base + 'sem-localize.' + b + '.js' + query;
    s.async = true;
    document.head.appendChild(s);
  }}

  function guessLang() {{
    try {{
      var stored = window.localStorage && localStorage.getItem('selectedLanguage');
      if (stored) {{
        var parsed = JSON.parse(stored);
        if (parsed && parsed !== 'null') return parsed;
      }}
    }} catch (e) {{ /* storage blocked — fall through */ }}
    return (navigator.language || 'en');
  }}

  function semLocalize(key, lang) {{
    lang = lang || 'en';
    // Exact match first, then base language (zh-Hans → zh, de-CH → de).
    var t = tables[lang];
    if (!t) {{
      var b = baseLang(lang);
      t = tables[b];
      if (!t) ensure(b);   // lazily fetch; English answers meanwhile
    }}
    t = t || tables.en || {{}};
    var fallback = tables.en || {{}};
    return t[key] || fallback[key] || key;
  }}

  window.semLocalize = semLocalize;
  ensure(guessLang());
  document.dispatchEvent(new CustomEvent('sem-localize-ready'));
}})();
"""

LANG_TEMPLATE = """// Auto-generated by build_localize.py from translations.json — do not edit manually
// Generated: {stamp}
// (#738) Language table '{lang}' — injected on demand by sem-localize.js.
(function() {{
  if (typeof window === 'undefined') return;
  var tables = window.__semLocalizeTables = window.__semLocalizeTables || {{}};
  tables['{lang}'] = {table};
  document.dispatchEvent(new CustomEvent('sem-localize-ready'));
}})();
"""


def generate(translations_path: str = TRANSLATIONS, out_dir: str = HERE) -> list:
    with open(translations_path, encoding="utf-8") as f:
        data = json.load(f)
    stamp = datetime.now(timezone.utc).isoformat()
    written = []

    def dump(table):
        return json.dumps(table, ensure_ascii=False, sort_keys=True,
                          separators=(",", ":"))

    loader = LOADER_TEMPLATE.format(stamp=stamp, en_table=dump(data.get("en", {})))
    path = os.path.join(out_dir, "sem-localize.js")
    with open(path, "w", encoding="utf-8") as f:
        f.write(loader)
    written.append(path)

    for lang, table in sorted(data.items()):
        if lang == "en":
            continue
        path = os.path.join(out_dir, f"sem-localize.{lang}.js")
        with open(path, "w", encoding="utf-8") as f:
            f.write(LANG_TEMPLATE.format(stamp=stamp, lang=lang, table=dump(table)))
        written.append(path)
    return written


if __name__ == "__main__":
    for p in generate():
        print(f"wrote {p} ({os.path.getsize(p)} bytes)")
