#!/usr/bin/env python3
"""Rank stale SEM modules as candidates for the v1.7.1 audit program.

Ranking score:

    score = log(LOC) * months_since_last_touch * decision_branch_density

where ``decision_branch_density`` is a per-line proxy for how many
silent-failure paths a module exposes (count of leading ``if`` / ``elif``
/ ``raise`` lines divided by LOC). High-LOC modules with old last-touched
dates and many branches rank highest.

Emits ``docs/AUDIT_BACKLOG.md`` ranked table; commit the result so the
backlog's evolution is visible across runs.

Usage::

    python3 tools/audit_candidates.py [--since 2025-12-01] [--top 15]

See ``docs/AUDIT_PLAYBOOK.md`` for the workflow each candidate goes
through once it's picked.
"""
from __future__ import annotations

import argparse
import math
import re
import subprocess
import sys
from datetime import date, datetime
from pathlib import Path


REPO = Path(__file__).resolve().parent.parent
EXCLUDE_PREFIXES = ("tests/", "tools/")
EXCLUDE_NAMES = {"__init__.py"}
BRANCH_RE = re.compile(r"^\s*(if |elif |else:|raise |except )", re.M)


def _run(cmd: list[str]) -> str:
    return subprocess.check_output(cmd, cwd=REPO, text=True).strip()


def _git_last_touched(path: str) -> date | None:
    """Last commit date for ``path``. ``None`` if file isn't in git."""
    out = _run(["git", "log", "-1", "--format=%cs", "--", path])
    if not out:
        return None
    return date.fromisoformat(out)


def _all_py_files() -> list[str]:
    out = _run(["git", "ls-files", "*.py"])
    return [
        p for p in out.splitlines()
        if not any(p.startswith(pref) for pref in EXCLUDE_PREFIXES)
        and Path(p).name not in EXCLUDE_NAMES
    ]


def _months_since(d: date) -> float:
    delta = date.today() - d
    return delta.days / 30.4375  # average month length


def _loc(path: str) -> int:
    return sum(1 for _ in (REPO / path).read_text(encoding="utf-8").splitlines())


def _branch_count(path: str) -> int:
    text = (REPO / path).read_text(encoding="utf-8")
    return len(BRANCH_RE.findall(text))


def rank(since: date, top: int) -> list[dict]:
    rows: list[dict] = []
    for path in _all_py_files():
        last = _git_last_touched(path)
        if last is None or last >= since:
            continue
        loc = _loc(path)
        if loc < 50:
            continue  # skip trivial files (__init__, tiny shims)
        branches = _branch_count(path)
        density = branches / loc if loc else 0.0
        months = _months_since(last)
        score = math.log(max(loc, 2)) * months * (density + 0.01)
        rows.append({
            "path": path,
            "loc": loc,
            "last": last.isoformat(),
            "months": round(months, 1),
            "branches": branches,
            "density": round(density, 3),
            "score": round(score, 2),
        })
    rows.sort(key=lambda r: r["score"], reverse=True)
    return rows[:top]


def render_backlog(rows: list[dict], since: date) -> str:
    today = date.today().isoformat()
    lines = [
        "# Audit Backlog — v1.7.1 Stabilization",
        "",
        f"_Generated by `tools/audit_candidates.py` on {today}_",
        f"_Cutoff: files untouched since {since.isoformat()}_",
        "",
        "Score formula: `log(LOC) × months_since_touch × (branch_density + 0.01)`.",
        "Higher score = more lines of code that have sat untouched longer with more",
        "decision branches (and thus more silent-failure surface area).",
        "",
        "See `docs/AUDIT_PLAYBOOK.md` for the workflow each candidate goes through.",
        "",
        "| # | Module | LOC | Last touched | Months | Branches | Density | Score | Audit issue |",
        "|---|--------|-----|--------------|--------|----------|---------|-------|-------------|",
    ]
    for i, r in enumerate(rows, 1):
        lines.append(
            f"| {i} | `{r['path']}` | {r['loc']} | {r['last']} | "
            f"{r['months']} | {r['branches']} | {r['density']} | {r['score']} | _not yet_ |"
        )
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--since", default="2026-05-01",
        help="cutoff date (YYYY-MM-DD); files touched on/after this are excluded",
    )
    parser.add_argument(
        "--top", type=int, default=15,
        help="report the top N candidates",
    )
    parser.add_argument(
        "--out", default="docs/AUDIT_BACKLOG.md",
        help="output path (relative to repo root)",
    )
    parser.add_argument(
        "--print-only", action="store_true",
        help="print the table to stdout, don't write the file",
    )
    args = parser.parse_args()

    since = datetime.strptime(args.since, "%Y-%m-%d").date()
    rows = rank(since, args.top)
    md = render_backlog(rows, since)
    if args.print_only:
        sys.stdout.write(md)
    else:
        out = REPO / args.out
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(md, encoding="utf-8")
        print(f"wrote {out.relative_to(REPO)} ({len(rows)} rows)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
